### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by silverjam**

### CODE REVIEW

**Comment by silverjam** [comment]
@KrasnikovEugene A mistake (confusion with the kernel makefiles KBUILD_OUTPUT), it should be KLIB_BUILD everywhere, I will correct, thanks.

**Comment by silverjam** [comment]
@KrasnikovEugene addressed your comments and added sign-off to both commit messages, thanks!

**Comment by KrasnikovEugene** [comment]
Just out of curiosity If you are not using android then what kind of HW are you using?:)

**Comment by silverjam** [comment]
We are using android but we are just "injecting" the wcn36xx driver into an
existing image... So no AOSP / cm build is required.

**Comment by KrasnikovEugene** [comment]
What do you understand under "injecting"? To build wcn36xx u still need kernel image/headers/objects right?

**Comment by silverjam** [comment]
I'm not really following how wcn36xx is supposed to build for CyanogenMod, Xperia Z (even the Xperia T) is using kernel version 3.4... so wcn36xx won't compile out of the box, yet the instructions don't mention using backports?

**Comment by silverjam** [comment]
@KrasnikovEugene the builds works with the build instructions here: https://github.com/KrasnikovEugene/wcn36xx/blob/master/backports/README-backports -- however... I'm assuming your thinking this would be invoked through the Android build system, right?

**Comment by KrasnikovEugene** [comment]
What do you mean? sorry did not get your question.
I will update build instruction in the nearest future so it should become more clear.

**Comment by silverjam** [comment]
My question is: how do I test that code path, and what is it's purpose?

I can hook things into the Android build system like this:
    https://gist.github.com/silverjam/acd4d8bfe1a0d44be6c5

...but this isn't testing the that code path...

**Comment by KrasnikovEugene** [comment]
I thought you can just try to build it using backports as described here https://github.com/KrasnikovEugene/wcn36xx/blob/master/backports/README-backports.
One idea came into my mind that most probably half of the Makefile can be removed since now we only use backports. Now we can not build wcn36xx directly with android. So that makes me think that we can clean up Makefiles.

**Comment by silverjam** [comment]
Created a new pull request for these changes https://github.com/KrasnikovEugene/wcn36xx/pull/141

**Pull request closed without merging**
